# Auto-generated pretrained GP hyperparameters for 3D quantum calibration
# Generated by: julia --project=. scripts/pretrain_gp_3d.jl
# θ layout: [logℓ₁, logℓ₂, logℓ₃, logσf, logc]
# Learned values: ℓ=[0.2252, 0.1802, 1.5], σf=0.7349, c=0.9487
pretrained_theta_3d() = [-1.4908317975294243, -1.7137113607265033, 0.40546510810816433, -0.30796817321037595, -0.05268031820900939]
