# Auto-generated pretrained GP hyperparameters for 3D quantum calibration
# Generated by: julia --project=. scripts/pretrain_gp_3d.jl
# θ layout: [logℓ₁, logℓ₂, logℓ₃, logσf, logc]
# Learned values: ℓ=[0.2205, 0.1807, 1.5], σf=0.6779, c=0.9487
pretrained_theta_3d() = [-1.5116339473091698, -1.7107140323002723, 0.40546510810816433, -0.38868460725212806, -0.05268027429417445]
