# All-seeds GP hyperparameters for variability analysis
# Generated by: julia --project=. scripts/pretrain_gp_3d.jl
# θ layout: [logℓ₁, logℓ₂, logℓ₃, logσf, logc]
pretrained_seeds() = [123806]
pretrained_theta_all() = [-1.4704036259461888, -1.5586720814796327, 0.40546510810816433, -0.36830663075334724]
