# All-seeds GP hyperparameters for variability analysis
# Generated by: julia --project=. scripts/pretrain_gp_3d.jl
# θ layout: [logℓ₁, logℓ₂, logℓ₃, logσf, logc]
pretrained_theta_3d() = [-1.5194082624528964, -1.716089280846524, 0.40546510810816433, -0.24741294851900966, -2.9957322735539904]
