# scripts/ms_sequence_search.jl
#
# Run the closed-loop MS Jacobian/Fisher search and print a concise summary of
# the best overall candidate, the A/B baselines, and the best distinct
# non-baseline sequence if one exists.

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."); io=devnull)
include(joinpath(@__DIR__, "..", "src", "CalibrationCode.jl"))
using .CalibrationCode

const CC = CalibrationCode
const SEARCH_RESULT_PATH = joinpath(@__DIR__, "..", "data", "ms_sequence_search_result.jl")

function format_pi_multiple(x::Float64)
    scaled = round(x / π; digits=3)
    return iszero(scaled) ? "0" : string(scaled, "π")
end

function describe_subgates(subgates)
    parts = String[]
    for subgate in subgates
        push!(parts, "MS_$(format_pi_multiple(subgate.phi))($(format_pi_multiple(subgate.theta)))")
    end
    return join(parts, " · ")
end

candidate_to_literal(candidate) = (
    family=candidate.family,
    nominal=candidate.nominal,
    score=candidate.score,
    info_area=candidate.info_area,
    balance_score=candidate.balance_score,
    readout_weight=candidate.readout_weight,
    max_corr=candidate.max_corr,
    singular_values=collect(candidate.singular_values),
    fisher_eigs=collect(candidate.fisher_eigs),
    column_norms=candidate.column_norms,
    subgates=[(theta=subgate.theta, phi=subgate.phi) for subgate in candidate.subgates],
)

function result_to_literal(result)
    return (
        t=100.0,
        candidate_count=result.candidate_count,
        filtered_candidate_count=result.filtered_candidate_count,
        matching_baseline=result.matching_baseline,
        omega_center=result.omega_center,
        I_center=result.I_center,
        best_overall=candidate_to_literal(result.best_overall),
        best_new=isnothing(result.best_new) ? nothing : candidate_to_literal(result.best_new),
        top_results=[candidate_to_literal(candidate) for candidate in result.top_results],
    )
end

function main()
    result = CC.search_ms_calibration_sequence(100.0)
    result_literal = result_to_literal(result)

    mkpath(dirname(SEARCH_RESULT_PATH))
    open(SEARCH_RESULT_PATH, "w") do io
        println(io, "# Auto-generated by scripts/ms_sequence_search.jl")
        show(io, result_literal)
        println(io)
    end

    @info "Best overall MS Jacobian candidate" matched_baseline=result.matching_baseline score=result.best_overall.score nominal=result.best_overall.nominal sequence=describe_subgates(result.best_overall.subgates)
    for spec in CC.default_ms_sequence_specs()
        baseline = result.baselines[spec.name]
        @info "Baseline sequence score" name=spec.name score=baseline.score nominal=baseline.nominal sequence=describe_subgates(baseline.subgates)
    end
    if !isnothing(result.best_new)
        @info "Best distinct non-baseline candidate" score=result.best_new.score nominal=result.best_new.nominal sequence=describe_subgates(result.best_new.subgates)
    end
    @info "Saved MS sequence search summary" path=SEARCH_RESULT_PATH
    return result
end

main()
