using Random
using Statistics
import Pkg
Pkg.activate(joinpath(@__DIR__, ".."))
Pkg.instantiate()

include(joinpath(@__DIR__, "..", "src", "CalibrationCode.jl"))
using .CalibrationCode

redirect_stderr(devnull)

# Same setup as opt_qnoisy_3d_parallel_benchmark.jl
const t = 100.0
base = CalibrationCode.ideal(t)
const f_cl0, f_sb0, A0 = base.f_cl, base.f_sb, base.A

const span_kHz = 2.0
const span_fcl = span_kHz * 1e3 * 2π
const span_fsb = span_kHz * 1e3 * 2π
const span_A = 1.2 * A0 - A0

u_to_params(u) = (f_cl0 + span_fcl * u[1],
    f_sb0 + span_fsb * u[2],
    A0 + span_A * u[3])

function Q_det_obj(u)
    fcl, fsb, A = u_to_params(u)
    return CalibrationCode.Q_varMS(t, fcl, fsb, A; N=1000, numMS=2)
end

const bounds = [(-1.0, 1.0), (-1.0, 1.0), (-1.0, 1.0)]
const n_pretrain = 500
const pretrain_seed = 42

println("=== Pretraining GP hyperparameters on Q_det (3D) ===")
println("Sampling $n_pretrain points with fixed seed=$pretrain_seed ...")
flush(stdout)

rng = Random.MersenneTwister(pretrain_seed)
d = length(bounds)
lb = Float64[b[1] for b in bounds]
ub = Float64[b[2] for b in bounds]

X_pre = Matrix{Float64}(undef, d, n_pretrain)
y_pre = Vector{Float64}(undef, n_pretrain)
σy_pre = zeros(n_pretrain)  # deterministic: zero noise

for i in 1:n_pretrain
    x = lb .+ rand(rng, d) .* (ub .- lb)
    X_pre[:, i] = x
    y_pre[i] = Q_det_obj(x)
    if i % 50 == 0
        println("  Sampled $i / $n_pretrain")
        flush(stdout)
    end
end

println("Fitting GP (n_restarts=12) ...")
flush(stdout)

gp = CalibrationCode.fit_heterogp(X_pre, y_pre, σy_pre;
    learn_hypers=true,
    learn_noise_scale=true,
    n_restarts=12,
    jitter=1e-8,
    rng=rng,
)

θ = gp.θ
ℓ = exp.(θ[1:d])
σf = exp(θ[d+1])
c = exp(θ[d+2])

println("\n=== Learned hyperparameters ===")
println("Lengthscales ℓ = ", round.(ℓ, digits=4))
println("Signal std   σf = ", round(σf, digits=4))
println("Noise scale  c  = ", round(c, digits=4))
println("θ (raw log-space) = ", round.(θ, digits=6))

# Save as a simple Julia loader file
output_path = joinpath(@__DIR__, "data", "pretrained_theta_3d.jl")
open(output_path, "w") do io
    println(io, "# Auto-generated pretrained GP hyperparameters for 3D quantum calibration")
    println(io, "# Generated by: julia --project=. scripts/pretrain_gp_3d.jl")
    println(io, "# θ layout: [logℓ₁, logℓ₂, logℓ₃, logσf, logc]")
    println(io, "# Learned values: ℓ=$(round.(ℓ, digits=4)), σf=$(round(σf, digits=4)), c=$(round(c, digits=4))")
    println(io, "pretrained_theta_3d() = ", repr(θ))
end

println("\nSaved to: $output_path")
println("Run opt_qnoisy_3d_parallel_benchmark.jl to use (set freeze_mode as desired).")
